CREATE TABLE [dbo].[PaaSAvailabilitySnapshot] (
    [paasAvailabilitySnapshotId] BIGINT           IDENTITY (1, 1) NOT NULL,
    [runId]                      UNIQUEIDENTIFIER NOT NULL,
    [capturedAtUtc]              DATETIME2 (7)    NOT NULL,
    [requestedService]           NVARCHAR (64)    NOT NULL,
    [requestedRegionPreset]      NVARCHAR (64)    NULL,
    [requestedRegionsJson]       NVARCHAR (MAX)   NULL,
    [metadataJson]               NVARCHAR (MAX)   NULL,
    [category]                   NVARCHAR (64)    NOT NULL,
    [service]                    NVARCHAR (64)    NOT NULL,
    [region]                     NVARCHAR (64)    NOT NULL,
    [resourceType]               NVARCHAR (64)    NULL,
    [name]                       NVARCHAR (256)   NOT NULL,
    [displayName]                NVARCHAR (256)   NULL,
    [edition]                    NVARCHAR (128)   NULL,
    [tier]                       NVARCHAR (256)   NULL,
    [family]                     NVARCHAR (128)   NULL,
    [status]                     NVARCHAR (64)    NULL,
    [available]                  BIT              NULL,
    [zoneRedundant]              BIT              NULL,
    [quotaCurrent]               INT              NULL,
    [quotaLimit]                 INT              NULL,
    [metricPrimary]              NVARCHAR (256)   NULL,
    [metricSecondary]            NVARCHAR (256)   NULL,
    [detailsJson]                NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_PaaSAvailabilitySnapshot] PRIMARY KEY CLUSTERED ([paasAvailabilitySnapshotId] ASC)
);
